# Generated by Django 5.0.1 on 2024-01-23 21:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ABOUT_US",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="عنوان")),
                (
                    "picture",
                    models.FileField(upload_to="ABOUT_US/IMAGE/", verbose_name="تصویر"),
                ),
                ("text", ckeditor.fields.RichTextField(verbose_name="متن ")),
            ],
            options={
                "verbose_name_plural": "درباره ما وبسایت",
                "db_table": "ABOUT_US",
            },
        ),
        migrations.CreateModel(
            name="Teams_Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=100, verbose_name="نام و نام خانوادگی"),
                ),
                (
                    "positions",
                    models.CharField(max_length=100, verbose_name="عنوان شغلی"),
                ),
                (
                    "text",
                    models.CharField(max_length=200, verbose_name="توضیحات تک خطی "),
                ),
            ],
            options={
                "verbose_name_plural": "اعضا برای معرفی در سایت",
                "db_table": "Teams_Member",
            },
        ),
    ]
