# Generated by Django 5.0.1 on 2024-01-23 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("BASE", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teams_member",
            name="picture",
            field=models.FileField(
                null=True, upload_to="Teams_Member/IMAGE/", verbose_name="تصویر عضو"
            ),
        ),
    ]
