# Generated by Django 5.0.1 on 2024-01-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("BASE", "0002_teams_member_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="SLIDE_POSTER",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="نام عکس")),
                (
                    "picture",
                    models.FileField(upload_to="SLIDER/IMAGE/", verbose_name="تصویر"),
                ),
            ],
            options={
                "verbose_name_plural": "تصاویر اسلایدر صفحه نخست",
                "db_table": "SLIDE_POSTER",
            },
        ),
    ]
