# Generated by Django 5.0.1 on 2024-01-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("BASE", "0003_slide_poster"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("q1", models.CharField(max_length=100, verbose_name="سوال 1 ")),
                ("a1", models.CharField(max_length=100, verbose_name="جواب 1 ")),
                ("q2", models.CharField(max_length=100, verbose_name="سوال 2 ")),
                ("a2", models.CharField(max_length=100, verbose_name="جواب 2 ")),
                ("q3", models.CharField(max_length=100, verbose_name="سوال 3 ")),
                ("a3", models.CharField(max_length=100, verbose_name="جواب 3 ")),
                ("q4", models.CharField(max_length=100, verbose_name="سوال 4 ")),
                ("a4", models.CharField(max_length=100, verbose_name="جواب 4 ")),
                ("q5", models.CharField(max_length=100, verbose_name="سوال 5 ")),
                ("a5", models.CharField(max_length=100, verbose_name="جواب 5 ")),
            ],
            options={
                "verbose_name_plural": "سوالات متداول",
                "db_table": "FAQ",
            },
        ),
    ]
