# Generated by Django 5.0.1 on 2024-01-27 10:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("BASE", "0004_faq"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faq",
            name="a2",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="a3",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="a4",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="a5",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="q2",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="q3",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="q4",
        ),
        migrations.RemoveField(
            model_name="faq",
            name="q5",
        ),
    ]
