# Generated by Django 5.0.1 on 2024-01-25 14:16

import ckeditor.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product_Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="عنوان دسته بندی"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        unique=True, verbose_name="آدرس اینترنتی دسته بندی "
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "دسته بندی محصولات وبسایت",
                "db_table": "Product_Category",
            },
        ),
        migrations.CreateModel(
            name="Tags_Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=20, unique=True, verbose_name="نام تگ"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="آدرس اینترنتی")),
            ],
            options={
                "verbose_name_plural": "تگ های محصولات ",
                "db_table": "Tags_Product",
            },
        ),
        migrations.CreateModel(
            name="Information_Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "picture1",
                    models.FileField(
                        upload_to="Product/IMAGE/", verbose_name="تصویر 1 محصول"
                    ),
                ),
                (
                    "picture2",
                    models.FileField(
                        upload_to="Product/IMAGE/", verbose_name="تصویر 2 محصول"
                    ),
                ),
                (
                    "picture3",
                    models.FileField(
                        upload_to="Product/IMAGE/", verbose_name="تصویر 3 محصول"
                    ),
                ),
                (
                    "picture4",
                    models.FileField(
                        upload_to="Product/IMAGE/", verbose_name="تصویر 4 محصول"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام محصول")),
                (
                    "description",
                    ckeditor.fields.RichTextField(verbose_name="توضحیات محصول"),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=0, default=0, max_digits=12),
                ),
                (
                    "is_sale",
                    models.BooleanField(
                        default=False, verbose_name="آیا تخفیف شامل میشود "
                    ),
                ),
                (
                    "percent_sale",
                    models.IntegerField(default=0, verbose_name="درصد تخفیف"),
                ),
                (
                    "marks",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Product_Category",
                        to="product.product_category",
                        verbose_name="دسته بندی",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        to="product.tags_product", verbose_name="تگ ها"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "محصولات وبسایت",
                "db_table": "Information_Product",
            },
        ),
    ]
