# Generated by Django 5.0.1 on 2024-01-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_alter_information_product_inventory"),
    ]

    operations = [
        migrations.AddField(
            model_name="information_product",
            name="showing",
            field=models.CharField(
                choices=[
                    ("featured", "محصولات منتخب"),
                    ("on-sale", "تخفیف خورده"),
                    ("most-visited", "پربازدید ترین"),
                ],
                max_length=20,
                null=True,
                verbose_name="دسته بندی برای نمایش ",
            ),
        ),
    ]
