# Generated by Django 5.0.1 on 2024-01-27 16:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0007_information_product_description_2"),
    ]

    operations = [
        migrations.AddField(
            model_name="information_product",
            name="naghd_barrasi",
            field=ckeditor.fields.RichTextField(
                null=True, verbose_name="نقد و بررسی محصول"
            ),
        ),
    ]
