# Generated by Django 5.0.1 on 2024-01-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0008_information_product_naghd_barrasi"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product_Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=100, verbose_name="نام و نام خانوادگی"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="ایمیل ")),
                ("text_comment", models.TextField(verbose_name="متن دیدگاه")),
            ],
            options={
                "verbose_name_plural": "نظرات در مورد محصولات",
                "db_table": "Product_Comment",
            },
        ),
    ]
