# Generated by Django 5.0.1 on 2024-01-27 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0009_product_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="product_comment",
            name="post",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.information_product",
                verbose_name="محصول مورد نظر ",
            ),
        ),
    ]
