# Generated by Django 5.0.1 on 2024-01-28 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0011_product_comment_creation"),
    ]

    operations = [
        migrations.AddField(
            model_name="product_category",
            name="picture",
            field=models.FileField(
                null=True,
                upload_to="Product_Category/IMAGE/",
                verbose_name="تصویر دسته بندی محصولات",
            ),
        ),
        migrations.AlterField(
            model_name="product_comment",
            name="post",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Information_Product",
                to="product.information_product",
                verbose_name="محصول مورد نظر ",
            ),
        ),
        migrations.CreateModel(
            name="Child1_detail_category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, verbose_name="نام ریز دسته بندی ها "
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Product_Category_2",
                        to="product.product_category",
                        verbose_name="دسته بندی کلی ",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "عنوان های ریز دسته بندی ها ",
                "db_table": "Child1_detail_category",
            },
        ),
        migrations.CreateModel(
            name="Detail_category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="نام دسته بندی")),
                ("slug", models.SlugField(unique=True, verbose_name="آدرس اینترنتی")),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Child1_detail_category",
                        to="product.child1_detail_category",
                        verbose_name="والد ",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "ریز دسته بندی ها ",
                "db_table": "Detail_category",
            },
        ),
    ]
