# Generated by Django 5.0.1 on 2024-01-28 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "product",
            "0012_product_category_picture_alter_product_comment_post_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="information_product",
            name="Detail_category1",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Detail_category1",
                to="product.detail_category",
                verbose_name="ریز دسته بندی ",
            ),
        ),
    ]
