# Generated by Django 5.0.1 on 2024-01-23 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog_Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="عنوان دسته بندی"),
                ),
                ("slug", models.SlugField(verbose_name="آدرس اینترنتی ")),
            ],
            options={
                "verbose_name_plural": "دسته بندی پست های وبلاگ",
                "db_table": "Blog_Category",
            },
        ),
        migrations.CreateModel(
            name="Tags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="عنوان تگ")),
                ("slug", models.SlugField(verbose_name="آدرس اینترنتی تگ")),
            ],
            options={
                "verbose_name_plural": "تگ های پست های وبلاگ",
                "db_table": "Tags",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "picture",
                    models.FileField(
                        upload_to="BLOG/POST/IMAGE/", verbose_name="عکس پست"
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="عنوان پست")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Blog_Category",
                        to="blog.blog_category",
                        verbose_name="دسته بندی این پست",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        to="blog.tags", verbose_name="تگ های این پست"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "پست ها ",
                "db_table": "Post",
            },
        ),
    ]
