# Generated by Django 5.0.1 on 2024-01-23 20:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="text",
            field=ckeditor.fields.RichTextField(null=True, verbose_name="متن پست"),
        ),
    ]
