# Generated by Django 5.0.1 on 2024-01-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_post_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="creation",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="زمان ساخت"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="modified",
            field=models.DateTimeField(null=True, verbose_name="تغییرات زمانی"),
        ),
    ]
