# Generated by Django 5.0.1 on 2024-01-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_post_creation_post_modified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="modified",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="تغییرات زمانی"
            ),
        ),
    ]
