# Generated by Django 5.0.1 on 2024-01-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="تاریخ انتشار"
            ),
        ),
    ]
