# Generated by Django 5.0.1 on 2024-01-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_comments_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[("d", "پیش نویس"), ("p", "انتشار")],
                default="d",
                max_length=10,
                null=True,
                verbose_name="وضعیت انتشار پست",
            ),
        ),
    ]
