# Generated by Django 5.0.1 on 2024-01-26 08:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0008_post_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="created",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                null=True,
                verbose_name="تاریخ انتشار",
            ),
        ),
    ]
