# Generated by Django 5.0.1 on 2024-01-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0009_alter_comments_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="many_visited",
            field=models.BooleanField(
                default=False, null=True, verbose_name="آیا جز موارد پربازدید است ؟"
            ),
        ),
    ]
