# Generated by Django 5.0.1 on 2024-01-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Information_Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.CharField(max_length=100, verbose_name="آدرس فروشگاه"),
                ),
                ("tel1", models.CharField(max_length=11, verbose_name="تلفن 1 ")),
                ("tel2", models.CharField(max_length=11, verbose_name="تلفن 2 ")),
                ("email", models.EmailField(max_length=254, verbose_name="ایمیل ")),
            ],
            options={
                "verbose_name_plural": "آدرس و مشخصات شرکت",
                "db_table": "Information_Company",
            },
        ),
        migrations.CreateModel(
            name="Send_Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=100, verbose_name="نام و نام خانوادگی"),
                ),
                ("phone", models.CharField(max_length=11, verbose_name="تلفن ")),
                ("email", models.EmailField(max_length=254, verbose_name="ایمیل")),
                ("text", models.TextField(verbose_name="متن پیام")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ساخت"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("N", "در انتظار پاسخ"),
                            ("Y", "پاسخ داده شده"),
                            ("C", "در حال رسیدگی"),
                        ],
                        default="N",
                        max_length=10,
                        verbose_name="وضعیت رسیدگی به پیام",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "پیام های ارسال شده از طرف فرم ارتباط با ما",
                "db_table": "Send_Message",
            },
        ),
    ]
