# Generated by Django 5.0.1 on 2024-01-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact_us", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="information_company",
            name="location",
            field=models.CharField(
                max_length=200, null=True, verbose_name="آدرس از روی نقشه"
            ),
        ),
    ]
