# Generated by Django 5.0.1 on 2024-01-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact_us", "0002_information_company_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="send_message",
            name="subject",
            field=models.CharField(max_length=50, null=True, verbose_name="موضوع پیام"),
        ),
    ]
